# //////////////////////////////////////////////////////////////////////////////////////////////////
# ///                                                                                            ///
# /// 1. Review the code in this file. Can you spot the bug?                                     ///
# /// 2. Fix the bug and push your solution so that GitHub Actions can run                       ///
# /// 3. You successfully completed this level when .github/workflows/jarvis-hack.yml pass ðŸŸ¢    ///
# /// 4. If you get stuck, read the hint in hint-1.txt and try again                             /// 
# /// 5. If you need more guidance, read the hint in hint-2.txt and try again                    ///
# /// 6. Compare your solution with solution.yml. Remember, there are several possible solutions ///
# ///                                                                                            ///
# //////////////////////////////////////////////////////////////////////////////////////////////////

name: CODE - Jarvis Gone Wrong

on:
  push:
    paths:
      - ".github/workflows/jarvis-code.yml"

jobs:
  jarvis:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Check GitHub Status
        # Source of GitHub Action in line 30: 
        # https://github.com/dduzgun-security/secure-code-game-action
        uses: dduzgun-security/secure-code-game-action@1c9ed9f1e57d7b8c4e9bfa8013fd54e322214eb4 # v2.0
        with:
          who-to-greet: "Jarvis, obviously ..."
          get-token: "token-4db56ee8-dbec-46f3-96f5-32247695ab9b"
